//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popov_Glaski_save.database
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Agent
    {
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int AgentTypeID { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string DirectorName { get; set; }
        public string Phone { get; set; }
        public string ClearPhone
        {
            get
            {
                return new string(Phone.Where(char.IsDigit).ToArray());
            }
        }
        public string Email { get; set; }
        public string Logo { get; set; }
        public string LogoPath
        {
            get
            {
                if (string.IsNullOrEmpty(Logo))
                {
                    return null;
                }

                return $"/res/images" + Logo;
            }
        }
        public int Priority { get; set; }

        public int TotalSalesUnits
        {
            get
            {
                int totalSales = 0;

                //DateTime startDate = DateTime.Now.AddDays(-365);

                foreach (ProductSale productSale in ProductSale)
                {
                    totalSales += productSale.ProductCount;
                }

                return totalSales;
            }
        }
        public decimal TotalSalesAmount
        {
            get
            {
                return ProductSale.Sum(ps => ps.TotalCost);
            }
        }
        public int Discount
        {
            get
            {
                if (TotalSalesAmount < 10000)
                    return 0;
                else if (TotalSalesAmount < 50000)
                    return 5;
                else if (TotalSalesAmount < 150000)
                    return 10;
                else if (TotalSalesAmount < 500000)
                    return 20;
                else
                    return 25;
            }
        }

        public virtual AgentType AgentType { get; set; }
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
